// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4eUqKn6fP0prd7OMy5PrQj1ohmKo0ZWM',
    appId: '1:1046973145003:web:568a75acc74ccae9fbfcee',
    messagingSenderId: '1046973145003',
    projectId: 'releifai',
    authDomain: 'releifai.firebaseapp.com',
    storageBucket: 'releifai.firebasestorage.app',
    measurementId: 'G-KW45ZRVTGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8-MVuiR4b7AHtin3vo9G0Z_jbglOCoPE',
    appId: '1:1046973145003:android:dfa6ae2b6ac96cdbfbfcee',
    messagingSenderId: '1046973145003',
    projectId: 'releifai',
    storageBucket: 'releifai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApGOGXxCHtBvqyEu89OQjh5A013sU88es',
    appId: '1:1046973145003:ios:becb1f174306ccdefbfcee',
    messagingSenderId: '1046973145003',
    projectId: 'releifai',
    storageBucket: 'releifai.firebasestorage.app',
    iosBundleId: 'com.example.releifai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApGOGXxCHtBvqyEu89OQjh5A013sU88es',
    appId: '1:1046973145003:ios:becb1f174306ccdefbfcee',
    messagingSenderId: '1046973145003',
    projectId: 'releifai',
    storageBucket: 'releifai.firebasestorage.app',
    iosBundleId: 'com.example.releifai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4eUqKn6fP0prd7OMy5PrQj1ohmKo0ZWM',
    appId: '1:1046973145003:web:dc40dd1d3e085171fbfcee',
    messagingSenderId: '1046973145003',
    projectId: 'releifai',
    authDomain: 'releifai.firebaseapp.com',
    storageBucket: 'releifai.firebasestorage.app',
    measurementId: 'G-5WVPVYS06X',
  );
}
